name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'
    - name: Install dependencies
      run: pip install mkdocs mkdocs-material
    - name: Build
      run: mkdocs build
    - name: Deploy
      uses: actions/deploy@v1
      with:
        provider: pages
        github-token: ${{ secrets.GITHUB_TOKEN }}
        folder: site
